### ISSUE TITLE
Name of image risingstack/alpine:3.4-v6.9.1-4.1.0

### ISSUE THREAD

**Issue by Zadvornyi** [RisingStack/docker-node#3]
I installed  risingstack/alpine:3.4-v6.9.1-4.1.0 image, however, I checked npm version and I got 3.8.10 and 6.9.1 node version. I was embarrassed, as I expected to get 4.1.0 and 6.9.1. Is this error in name of image?

**Comment by tothandras** [comment]
Hi @Zadvornyi, the last tag doesn't stand for the npm version. Take a look at the [README](https://github.com/RisingStack/docker-node#tags).

**Comment by Zadvornyi** [comment]
Hi thanks
